---
- name: Install Java 6
  command: yum install -y java-1.6.0-openjdk
  sudo: true

- name: Extract archive
  unarchive: src=apache-tomcat-6.0.43.zip dest=/opt owner=vagrant group=vagrant creates=/opt/apache-tomcat-6.0.43

- name: Symlink tomcat dir
  file: src=/opt/apache-tomcat-6.0.43 path=/opt/tomcat state=link

- name: Change ownership
  file: path=/opt/tomcat owner=vagrant group=vagrant state=directory recurse=yes

- name: Install Tomcat init script
  copy: src=tomcat.sh dest=/etc/init.d/tomcat mode=0755
